# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e25d6f27cc14b154af7b78d046468f2ab3a64f6be99303df7cc55db214aa7cb255186f016b6f9db80becb34db14f8c3896a7cac2156fc40cf9d8caacd0a12f38

test:
  secret_key_base: 2930cb4e23d58706ca5bbb10b3beb08918dd469422aa03331bf17d6cc01452ebe48c65228f0c5b2df86f9b9e9cc56afcb9f7868218ff801837ae1dd03dd6c297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
